monitor.bluez.rules = [
  {
    matches = [
      {
        device.form-factor = "phone"
      }
    ]
    actions = {
      update-props = {
        bluez5.profile = "off"
        bluez5.auto-connect = []
      }
    }
  }
]
